FROM --platform=linux/amd64 mysql:8

# COPY ./gen /opt/gen

# RUN cd /opt/gen \
#     && ./bin/gen-initial-dataset \
#     && mv isucon7q-initial-dataset.sql.gz /docker-entrypoint-initdb.d/002_isucon7q-initial-dataset.sql.gz6